package com.nikoarap.slotmachine.other

import android.graphics.Color

object Constants {

    //DATA BASE NAME
    const val JACKPOT_DATABASE_NAME= "jackpot_db"

    // SHARED PREFERENCE NAME AND KEYS
    const val SHARED_PREFERENCES_NAME="sharedPref"
    const val KEY_TOGGLE_FIRST_TIME="KEY_TOGGLE_FIRST_TIME"
    const val KEY_BIG_PRIZE="KEY_BIG_PRIZE"
    const val KEY_SECOND_PRIZE="KEY_SECOND_PRIZE"
    const val KEY_SECOND_PRIZE_FIRST="KEY_SECOND_PRIZE_FIRST"
    const val KEY_SECOND_PRIZE_SECOND="KEY_SECOND_PRIZE_SECOND"
    const val KEY_SECOND_PRIZE_THIRD="KEY_SECOND_PRIZE_THIRD"
    const val KEY_THIRD_PRIZE="KEY_THIRD_PRIZE"
    const val KEY_THIRD_PRIZE_FIRST="KEY_THIRD_PRIZE_FIRST"
    const val KEY_THIRD_PRIZE_SECOND="KEY_THIRD_PRIZE_SECOND"
    const val KEY_THIRD_PRIZE_THIRD="KEY_THIRD_PRIZE_THIRD"
    const val KEY_THIRD_PRIZE_FOURTH="KEY_FOURTH_PRIZE_THIRD"
    const val KEY_MORNING_HOURS="KEY_MORNING_HOURS"
    const val KEY_EVENING_HOURS="KEY_EVENING_HOURS"
    const val KEY_NEW_USER ="KEY_NEW_USER"
    const val KEY_NAME="KEY_NAME"
    const val KEY_Email="KEY_Email"
    const val KEY_PHONE="KEY_PHONE"
    const val KEY_PRIZE="KEY_PRIZE"



    //SNACKBAR TEXTS FOR FAILS OR SUCCESS
    const val ENTER_ALL_VALUES=" please enter all the values"
    const val USER_SAVED_SUCCESSFULLY="USER_SAVED_SUCCESSFULLY"
    const val CHANGES_MADE_SUCCESSFULLY="CHANGES_MADE_SUCCESSFULLY"
}